### DISCUSSION TITLE
Test Config

### DISCUSSION THREAD

**Discussion by alafad** [Second-Hand-Friends/kleinanzeigen-bot#27] [Q&A] [answered]
Hello ,

can anybody please send me the 2 config files with an functional example? (Please grey out the Credentials)
I have the Problem, that i couldnt run the Code with my own example and i will prevent failures from me.

Thank You

**Comment by sebthom** [comment, marked as answer]
My `config.yaml` file looks something like this:

```yaml
ad_files:
  - "ads/ad_*.yaml"

ad_defaults:
  description:
    suffix: |

      Privatverkauf. Keine Gewährleistung.
  contact:
    name: Sebastian
    street: "<REMOVED>"
    zipcode: "<REMOVED>"

login:
  username: "<REMOVED>@<REMOVED>"
  password: "<REMOVED>"
```

My `ad_webcam.yaml` looks like this:
```yaml
active: true
category: 161/168/ja/
title: Indoor WLAN WebCam Infrarot Bewegungsmelder 1080p HD
description: |
  Gebraucht. Funktionsfähig. Originalverpackung

  - WLAN oder Verbindung via Netzwerkkabel
  - Bewegungs- und Geräuscherkennung
  - Infrarot Nachtsicht
  - inkl. Wandhalterung
price: 29
images:
  - images/webcam*.jpg
```

My file layout is like this:
```
D:\kleinanzeigen
  |- kleinanzeigen-bot.exe
  |- config.yaml
  |- ads/
      |- images/
      |   |- webcam1.jpg
      |   |- webcam2.jpg
      |- ad_webcam.yaml
```

I execute:
```bash
cd D:\kleinanzeigen
kleinanzeigen-bot publish --config config.yaml
````
