### DISCUSSION TITLE
How fill categories field in config.yaml ?

### DISCUSSION THREAD

**Discussion by OlegLoewen** [Second-Hand-Friends/kleinanzeigen-bot#31] [Q&A] [answered]
What the format to fill the field `categories` in config.yaml?

**Comment by sebthom** [comment, marked as answer]
It's a map.

```yaml
categories:
  Fernseher: 161/175/fernseher
  Sammeln: 185/234/sonstige
```
