### ISSUE TITLE
Problem with Shipping Selection

### ISSUE THREAD

**Issue by iamxnuel** [Second-Hand-Friends/kleinanzeigen-bot#118]
When I try to publish an ad with this config:

```yaml
active: true
type: OFFER
title: Räder Audi Test
description: >-
  Artikelnummer: 1000028619
  Modell: Test
  Marke: Audi
  VIN: WAUZZZ4G0HN126959
  Felgenteilenummer: 4G0 601 025 P
  Typ: 0588 BCA
  Reifenmarke: Michelin Pilot Alpin PA4
  Breite: 235
  Höhe: 45
  Zoll: 19
  Reifenindex: 99V
  Profiltiefe: 5, 6
  Einpresstiefe: 33
  Lochkreis: 5x112
  Felgengröße: 7,5x19
  Dot: 1017
  Dot Jahr: 2017
  Sommer / Winter: Winter
category: 210/223/reifen_felgen
price: 155
price_type: FIXED
special_attributes:
shipping_type: SHIPPING
shipping_costs: 25.95
images:
  - C:/Users/..../ImageStore/b82f62d8-1db5-4c98-82a7-033f6eef7fa4+5669a2c2-eae8-47fa-8337-08d904f3f65d.jpg
  - C:/Users/..../ImageStore/b82f62d8-1db5-4c98-82a7-033f6eef7fa4+e55282c2-9adb-4f10-b6e3-e163fee820a3.jpg
contact:
  name: Test
  street: Test
  zipcode: '01067'
  phone: ''
republication_interval: 1
```

the Bot runs but doesn't select the shipping type, so ebay Kleinanzeigen says "Please select shipping"
