### ISSUE TITLE
Multiline description leads to broken yaml after running bot

### ISSUE THREAD

**Issue by stkr22** [Second-Hand-Friends/kleinanzeigen-bot#123]
If multiline yaml is used like:

```yaml
active: true
type: OFFER
title: My Car
description: |

  lorem ipsum
```

kleinanzeigen bot will add a "4" after updating the yaml:

```yaml
active: true
type: OFFER
title: My Car
description: |4

  lorem ipsum
```

Only happens if multiline starts with new line.
