### ISSUE TITLE
NoSuchElementException: Message: Failed to set special attribute [Art] "Gesellschaftsspiele"

### ISSUE THREAD

**Issue by provinzio** [Second-Hand-Friends/kleinanzeigen-bot#126]
Started using the app, downloaded my ads and when trying to republish, I receive the following error:

`NoSuchElementException: Message: Failed to set special attribute [Art]`

This is my ad config file

```yaml
active: true
type: OFFER
title: ...
description: "..."
category: 17/23
special_attributes:
  Art: Gesellschaftsspiele
price: 20.0
price_type: FIXED
shipping_type: SHIPPING
shipping_costs: 5.95
images:
  - ad_0000000000__img1.jpg
contact:
  zipcode: '00000'
  name: ...
  street:
  phone:
republication_interval: 7
id: 0000000000
created_on: "2022-01-01 00:00:00"
updated_on:
```
