### ISSUE TITLE
Download exports city as contact:name to ad yaml file

### ISSUE THREAD

**Issue by provinzio** [Second-Hand-Friends/kleinanzeigen-bot#127]
Heyho, started using your bot by downloading my current ads and trying to republish.

After downloading, I saw that contact:name was filled with the city, but this field is used as name contact/person name when publishing.

```yaml
active: true
type: OFFER
title: ...
description: "..."
category: 17/23
special_attributes:
  Art: Gesellschaftsspiele
price: 20.0
price_type: FIXED
shipping_type: SHIPPING
shipping_costs: 5.95
images:
  - ad_0000000000__img1.jpg
contact:
  zipcode: '00000'
  name: WHEN DOWNLOADING THIS IS A CITY BUT SHOULD BE THE PERSON
  street:
  phone:
republication_interval: 7
id: 0000000000
created_on: 2022-01-01 00:00:00
updated_on:
```
