### ISSUE TITLE
IP got blocked! 

### ISSUE THREAD

**Issue by lamyergeier** [Second-Hand-Friends/kleinanzeigen-bot#152]
Any suggestions if it's possible to unblock the IP?

**Comment by PhilK-7** [comment]
The same happened to me at some point. Are you by any chance using a VPN? If so, you could switch to another IP. If not, try another method e.g. a proxy. The website defense measures have gotten more aggressive in recent time

**Comment by Bastilla123** [comment]
This has nothing to do with IP Address. I can with same credentials and on same device with same IP Login with Firefox and not with Google Chrome. I have feeling, that header is another. I try same with selenium firefox driver...

Can someone confirm that Google Chrome is blocked but Firefox works?

**Comment by Bastilla123** [comment]
This is very strange when i use this bot i get everytime my IP are blocked when i manual login then i can login.... i solve captcha with bot everytime manual... so selenium makes it another then i am make manual ... strange

**Comment by lamyergeier** [comment]
This is what happens to me: when i use the bot it says that my ip is blocked but i can log in manually!

**Comment by Lennix** [comment]
It may be due to sec-ch-ua header not being set by chromium and thats checked by the firewall.
I changed the user-agent to firefox and its working for me now.

``- --user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0``
Add this under browser.arguments in the config.yaml

**Comment by lamyergeier** [comment]
@Lennix  I am using Ubuntu 22.10. Can you please temm me how can I find the user agent value for my firefox? I am using version 108.0.2

**Comment by van-shorty** [comment]
define in the config file:
  user_data_dir: "" # see https://github.com/chromium/chromium/blob/main/docs/user_data_dir.md
  profile_name: "" --> normaly default

then chrome opens with the default profile as you use when starting chrome from windows, then everything works.
the problem is, that every time you start the tool chrome create a new session profile and then the same ip sends multiple session requests to ebay kleinanzeigen and that will be blocked.

**Comment by jeromewh** [comment]
I'm experiencing the same error.
The suggested workarounds by @van-shorty and @Lennix did not work.
Is there any information I can provide?

**Comment by van-shorty** [comment]
did you define this in your config?

` binary_location: C:\Program Files\Google\Chrome\Application\chrome.exe`

**Comment by jeromewh** [comment]
Weird... I tried it again (I just uncommented the lines from my previous tries) and now it works

Here is my current configuration:
```
browser:
  arguments:
    - --disable-dev-shm-usage
    - --no-sandbox
    - --user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0
  binary_location: 'C:\Program Files\Google\Chrome\Application\chrome.exe'
  extensions: []
  use_private_window: true
  user_data_dir: 'C:\Users\username\AppData\Local\Google\Chrome\User Data'
  profile_name: "Default"
```

I'll post again if get any more errors.
