### ISSUE TITLE
Chromedriver not found 

### ISSUE THREAD

**Issue by alafad** [Second-Hand-Friends/kleinanzeigen-bot#224]
Hello,

 since the last update from my Ubuntu 22.04 i get the following error message:
 
```
SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
```

I've  tried to rollback a few version and swap the chromedriver path, but I still get this error or a chromedriver not found error.

The same problem exists for me if I'am using the docker compose prebuild with the standard config:

```yaml
  - ./**/ad_*.{json,yml,yaml}

# default values for ads, can be overwritten in each ad configuration file
ad_defaults:
  active: true
  type: OFFER # one of: OFFER, WANTED
  description:
    prefix: ''
    suffix: ''
  price_type: NEGOTIABLE # one of: FIXED, NEGOTIABLE, GIVE_AWAY, NOT_APPLICABLE
  shipping_type: SHIPPING # one of: PICKUP, SHIPPING, NOT_APPLICABLE
  sell_directly: false # requires shipping_options to take effect
  contact:
    name: ''
    street: ''
    zipcode:
    phone: '' # IMPORTANT: surround phone number with quotes to prevent removal of leading zeros
  republication_interval: 7 # every X days ads should be re-published

# additional name to category ID mappings, see default list at
# https://github.com/Second-Hand-Friends/kleinanzeigen-bot/blob/main/kleinanzeigen_bot/resources/categories.yaml
# Notebooks: 161/278 # Elektronik > Notebooks
# Autoteile: 210/223/sonstige_autoteile # Auto, Rad & Boot > Autoteile & Reifen > Weitere Autoteile
categories: []

# browser configuration
browser:
  # https://peter.sh/experiments/chromium-command-line-switches/
  arguments:
    # https://stackoverflow.com/a/50725918/5116073
    - --disable-dev-shm-usage
    - --no-sandbox
    # --headless
    # --start-maximized
  binary_location: # path to custom browser executable, if not specified will be looked up on PATH
  extensions: [] # a list of .crx extension files to be loaded
  use_private_window: true
  user_data_dir: '' # see https://github.com/chromium/chromium/blob/main/docs/user_data_dir.md
  profile_name: ''

# login credentials
login:

```
