### ISSUE TITLE
[BUG] Failed to set special attribute [kueche_esszimmer.color_s]

### ISSUE THREAD

**Issue by euberdeveloper** [Second-Hand-Friends/kleinanzeigen-bot#281]
### ✔️ Expected Behaviour

It whould work

### 🐞 Actual Behaviour

It gives the following error: ```TimeoutError: Failed to set special attribute [kueche_esszimmer.color_s]```

### 📋 Steps to Reproduce

```
active: true
type: OFFER
title: XXX
description: XXX
category: 80l16387/86l16387
special_attributes:
  kueche_esszimmer.color_s: sonstige
  kueche_esszimmer.art_s: geschirr
  kueche_esszimmer.condition_s: ok
price: 7
price_type: NEGOTIABLE
shipping_type: NOT_APPLICABLE
shipping_costs:
shipping_options:
sell_directly:
images:
  - ad_yyy__img1.jpg
contact:
  zipcode: 'XXX'
  name: XXX
  street:
  phone:
republication_interval: 3
id: XXX
created_on: '2024-02-16T00:00:00'
updated_on:
```

### 📃 Relevant log output (if applicable)

```
[INFO] Deleting ad 'YYY' if already present...
[INFO]  ... pausing for 1954 ms ...
[INFO] Publishing ad 'YYY'...
[INFO]  ... pausing for 2225 ms ...
[INFO]  ... pausing for 1690 ms ...
[INFO]  ... pausing for 1796 ms ...
[INFO]  ... pausing for 2484 ms ...
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
args ({'code': -32000, 'message': 'Invalid search result range'},) kwargs {}
args ({'code': -32000, 'message': "DOM agent hasn't been enabled"},) kwargs {}
[ERROR] TimeoutError: Failed to set special attribute [kueche_esszimmer.color_s]
[73099] Failed to execute script '__main__' due to unhandled exception!
successfully removed temp profile /home/XXX/.config/google-chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
