### ISSUE TITLE
[BUG] TimeoutError: Condition not met within 20 seconds

### ISSUE THREAD

**Issue by student-sx** [Second-Hand-Friends/kleinanzeigen-bot#346]
### ✔️ Expected Behaviour

Successfully uploading an ad.

### 🐞 Actual Behaviour

Before finishing uploading an ad, the bot stops with an 20 second timeout error.

### 📋 Steps to Reproduce

```
./kleinanzeigen-bot --ads=due publish
```
My browser config is:

```
# browser configuration
browser:
  # https://peter.sh/experiments/chromium-command-line-switches/
  arguments:
  - --disable-dev-shm-usage
  - --no-sandbox
  binary_location: # path to custom browser executable, if not specified will be looked up on PATH
  extensions: [] # a list of .crx extension files to be loaded
  use_private_window: true
  user_data_dir: '' # see https://github.com/chromium/chromium/blob/main/docs/user_data_dir.md
  profile_name: ''
```

Bot-Version: 2024+1b326c1

Chromium-Browser Version: 130.0.6723.116 (Official Build) snap (64-bit)

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome

### 💻 What operating systems are you seeing the problem on? (if applicable)

Linux

### 📃 Relevant log output (if applicable)

```
... pausing for 1546 ms ...
[ERROR] TimeoutError: Condition not met within 20 seconds
[PYI-369936:ERROR] Failed to execute script '__main__' due to unhandled exception!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
